#!/usr/bin/env ruby
#^syntax detection

forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/apt'
mod 'thomasvandoren/redis'
mod 'elasticsearch/logstash'
mod 'elasticsearch/elasticsearch'
mod 'ispavailability/file_concat'
mod 'garethr/kibana'
